training_data = [

    #Change Contact Details
    {"text": "How can I update my contact details?", "label": "change_contact_details"},
    {"text": "I want to change my phone number.", "label": "change_contact_details"},
    {"text": "What’s the process for updating my email address?", "label": "change_contact_details"},
    {"text": "Can I update my address through online banking?", "label": "change_contact_details"},
    {"text": "How do I change my contact information in the app?", "label": "change_contact_details"},
    {"text": "I need to update my mailing address.", "label": "change_contact_details"},
    {"text": "How do I edit my email and phone number?", "label": "change_contact_details"},
    {"text": "What’s the procedure for updating my contact info?", "label": "change_contact_details"},
    {"text": "Can I modify my address for credit card statements?", "label": "change_contact_details"},
    {"text": "Is it possible to change my mobile number for OTPs?", "label": "change_contact_details"},
    {"text": "How long does it take to update my contact details?", "label": "change_contact_details"},
    {"text": "Steps to update my phone number?", "label": "change_contact_details"},
    {"text": "I want to change my email address in my profile.", "label": "change_contact_details"},
    {"text": "Can I update my contact details through the OCBC app?", "label": "change_contact_details"},
    {"text": "What are the steps to modify my personal details?", "label": "change_contact_details"},
    {"text": "How do I update my details like address or email?", "label": "change_contact_details"},
    {"text": "Can I change my phone number linked to my account?", "label": "change_contact_details"},
    {"text": "What’s the fastest way to update my address?", "label": "change_contact_details"},
    {"text": "Do I need a token to update my phone number?", "label": "change_contact_details"},
    {"text": "Can I update my address for all my accounts?", "label": "change_contact_details"},
    {"text": "How to update my personal contact information?", "label": "change_contact_details"},
    {"text": "Can I change my details through customer service?", "label": "change_contact_details"},
    {"text": "How can I change my phone number for SMS OTPs?", "label": "change_contact_details"},
    {"text": "I need to modify my mailing address for my account.", "label": "change_contact_details"},
    {"text": "What are the steps for updating my email and address?", "label": "change_contact_details"},
    {"text": "I want to update my phone number on file.", "label": "change_contact_details"},
    {"text": "How do I change my address for my savings account?", "label": "change_contact_details"},
    {"text": "Can I update my phone number without visiting a branch?", "label": "change_contact_details"},
    {"text": "How do I change my contact details on Internet Banking?", "label": "change_contact_details"},
    {"text": "What’s the procedure to update my mailing address?", "label": "change_contact_details"},

    #Retrieve Access Code
    {"text": "How do I retrieve my access code?", "label": "retrieve_access_code"},
    {"text": "What’s the process to get my access code back?", "label": "retrieve_access_code"},
    {"text": "I forgot my access code. How can I get it?", "label": "retrieve_access_code"},
    {"text": "Steps to recover my access code?", "label": "retrieve_access_code"},
    {"text": "Can I retrieve my access code online?", "label": "retrieve_access_code"},
    {"text": "I lost my access code. What should I do?", "label": "retrieve_access_code"},
    {"text": "How can I recover my OCBC access code?", "label": "retrieve_access_code"},
    {"text": "I need help finding my access code.", "label": "retrieve_access_code"},
    {"text": "Can I reset my access code?", "label": "retrieve_access_code"},
    {"text": "How do I get a new access code?", "label": "retrieve_access_code"},
    {"text": "What’s the fastest way to retrieve my access code?", "label": "retrieve_access_code"},
    {"text": "Can I use the app to recover my access code?", "label": "retrieve_access_code"},
    {"text": "How do I retrieve my OCBC banking access code?", "label": "retrieve_access_code"},
    {"text": "Where can I request my lost access code?", "label": "retrieve_access_code"},
    {"text": "What should I do if I can’t remember my access code?", "label": "retrieve_access_code"},
    {"text": "Steps to get back my access code?", "label": "retrieve_access_code"},
    {"text": "How to retrieve my access code through Internet Banking?", "label": "retrieve_access_code"},
    {"text": "Can I retrieve my access code without visiting a branch?", "label": "retrieve_access_code"},
    {"text": "I need help recovering my access code for my account.", "label": "retrieve_access_code"},
    {"text": "How do I recover my Internet Banking access code?", "label": "retrieve_access_code"},
    {"text": "Can I retrieve my access code via phone banking?", "label": "retrieve_access_code"},
    {"text": "I don’t have my access code. How can I recover it?", "label": "retrieve_access_code"},
    {"text": "Can I get my access code reissued online?", "label": "retrieve_access_code"},
    {"text": "How do I retrieve my login access code?", "label": "retrieve_access_code"},
    {"text": "What’s the procedure to recover a lost access code?", "label": "retrieve_access_code"},
    {"text": "Can I request a new access code if I lost mine?", "label": "retrieve_access_code"},
    {"text": "How do I retrieve my access code for Internet Banking?", "label": "retrieve_access_code"},
    {"text": "I lost my login credentials. How do I get my access code back?", "label": "retrieve_access_code"},
    {"text": "What are the steps to retrieve my access code online?", "label": "retrieve_access_code"},
    {"text": "How do I recover my access code if I forget it?", "label": "retrieve_access_code"},
]

validation_data = [
    #Change Contact Details
    {"text": "How do I update my phone number for my account?", "label": "change_contact_details"},
    {"text": "Can I modify my email address through the app?", "label": "change_contact_details"},
    {"text": "Steps to change my contact information?", "label": "change_contact_details"},
    {"text": "I want to update my mailing address for my credit card.", "label": "change_contact_details"},
    {"text": "What’s the process for editing my email and phone number?", "label": "change_contact_details"},
    {"text": "How long does it take to change my contact details?", "label": "change_contact_details"},
    {"text": "Can I update my personal details online?", "label": "change_contact_details"},
    {"text": "Is it possible to change my address for all accounts?", "label": "change_contact_details"},

    #Retrieve Access Code
    {"text": "I forgot my Internet Banking access code.", "label": "retrieve_access_code"},
    {"text": "How do I recover my lost access code?", "label": "retrieve_access_code"},
    {"text": "What’s the fastest way to get back my access code?", "label": "retrieve_access_code"},
    {"text": "Can I retrieve my access code without visiting OCBC?", "label": "retrieve_access_code"},
    {"text": "How can I get my access code if I forgot it?", "label": "retrieve_access_code"},
    {"text": "I need to reset my access code for Internet Banking.", "label": "retrieve_access_code"},
    {"text": "How do I retrieve my OCBC login code?", "label": "retrieve_access_code"},
    {"text": "What are the steps to recover my banking access code?", "label": "retrieve_access_code"},
]